### ISSUE TITLE
vs2013 build error

### ISSUE THREAD

**Issue by stonedreamforest** [JLospinoso/gargoyle#8] opened 2017-05-18 01:29 UTC
1>------ 已启动生成:  项目: Gargoyle, 配置: Debug Win32 ------
1>  main.cpp
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(14): error C2146: 语法错误: 缺少“;”(在标识符“DWORD”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(14): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(15): error C2146: 语法错误: 缺少“;”(在标识符“size_t”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(15): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(15): error C2086: “int `anonymous-namespace'::constexpr”: 重定义
1>          c:\users\administrator\desktop\gargoyle-master\main.cpp(14) : 参见“`anonymous-namespace'::constexpr”的声明
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(19): error C2146: 语法错误: 缺少“;”(在标识符“relative_offset”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(19): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(37): error C2440: “初始化”: 无法从“initializer-list”转换为“std::vector<`anonymous-namespace'::VersionToOffset,std::allocator<_Ty>>”
1>          with
1>          [
1>              _Ty=`anonymous-namespace'::VersionToOffset
1>          ]
1>          无构造函数可以接受源类型，或构造函数重载决策不明确
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(40): error C2146: 语法错误: 缺少“;”(在标识符“initialized”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(40): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(42): error C2146: 语法错误: 缺少“;”(在标识符“setup_length”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(42): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(50): error C2146: 语法错误: 缺少“;”(在标识符“interval”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(50): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(52): error C2146: 语法错误: 缺少“;”(在标识符“shadow”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(52): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(60): error C2146: 语法错误: 缺少“;”(在标识符“size”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(60): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(61): error C2146: 语法错误: 缺少“;”(在标识符“protections”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(61): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(63): error C2146: 语法错误: 缺少“;”(在标识符“old_protections”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(63): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(69): error C2146: 语法错误: 缺少“;”(在标识符“stack”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(69): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(69): error C2057: 应输入常量表达式
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(97): error C2146: 语法错误: 缺少“;”(在标识符“get_mshtml_gadget_relative_offset”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(97): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(130): error C2146: 语法错误: 缺少“;”(在标识符“relative_offset”的前面)
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(130): error C2065: “relative_offset”: 未声明的标识符
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(133): error C2065: “relative_offset”: 未声明的标识符
1>c:\users\administrator\desktop\gargoyle-master\main.cpp(133): fatal error C1903: 无法从以前的错误中恢复；正在停止编译
========== 生成:  成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

I did not find a way to resolve it

**Comment by JLospinoso** [comment] 2017-05-18 01:31
Hi @stonedreamforest, VS 2013 doesn't support `constexpr`. This is probably the cause of the issue, but I can't read the error message fully :)

I'd suggest compiling with VS2017 if that's possible.

**Comment by stonedreamforest** [comment] 2017-05-18 01:37
I do not have version 2017,  Thanks for such quick response :)

**Comment by JLospinoso** [comment] 2017-05-18 01:40
@stonedreamforest ok! Well if you remove the `constexpr` modifiers, it may still compile. I'd have to take a closer look though...

I'll close the issue, please re-open if you get the same problem on VS2017

**Closed as completed by JLospinoso** 2017-05-18 01:40 UTC
